# Generated by Django 5.0.3 on 2024-03-31 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projectmanager_project_projectmanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='projectmanager',
        ),
        migrations.DeleteModel(
            name='ProjectManager',
        ),
    ]
